// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MtgCollectionMgr.Models;

namespace MtgCollectionMgr.Migrations
{
    [DbContext(typeof(MtgCollectionMgrContext))]
    partial class MtgCollectionMgrContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MtgCollectionMgr.Models.CardCollectionModel", b =>
                {
                    b.Property<int>("CardModelID");

                    b.Property<int>("UserID");

                    b.Property<int>("Quantity");

                    b.HasKey("CardModelID", "UserID");

                    b.HasIndex("UserID");

                    b.ToTable("CardCollections");
                });

            modelBuilder.Entity("MtgCollectionMgr.Models.CardModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("BuylistMarketPrice");

                    b.Property<string>("ImageUrl");

                    b.Property<double>("MarketPrice");

                    b.Property<double>("MedianPrice");

                    b.Property<int?>("MultiverseId");

                    b.Property<string>("Name");

                    b.Property<string>("SetName");

                    b.HasKey("ID");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("MtgCollectionMgr.Models.UserModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Password");

                    b.Property<string>("Username");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MtgCollectionMgr.Models.CardCollectionModel", b =>
                {
                    b.HasOne("MtgCollectionMgr.Models.CardModel", "CardModel")
                        .WithMany("CardCollectionModels")
                        .HasForeignKey("CardModelID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MtgCollectionMgr.Models.UserModel", "User")
                        .WithMany("CardCollection")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
